#!/usr/bin/env python3
"""04_svch_kondensatory.csv → js/capacitors-data.js"""
import csv, json, sys, re
sys.stdout.reconfigure(encoding='utf-8')

CSV_PATH = r"d:/site/_data/04_svch_kondensatory.csv"
OUT_PATH = r"d:/site/js/capacitors-data.js"

BASE = '../assets/images/products/'

SERIES_META = {
    'ARC70A': ('arc70a', 'ARC70A', 'main', 'ТКЕС.434410.002 ТУ',
               'Сверхвысокочастотные многослойные керамические чип-конденсаторы серии ARC70A.',
               BASE + 'items/ARC70A 1.webp'),
    'ARC70C': ('arc70c', 'ARC70C', 'dev',  '',
               'СВЧ-конденсаторы серии ARC70C. В разработке.',
               BASE + 'capacitors.webp'),
    'ARC70E': ('arc70e', 'ARC70E', 'dev',  '',
               'СВЧ-конденсаторы серии ARC70E. В разработке.',
               BASE + 'capacitors.webp'),
}

def clean(s):
    return (s or '').strip().replace('\u00a0', ' ')

def strip_html(s):
    return re.sub(r'<[^>]+>', '', s or '').strip()

def detect(name):
    for b in ('ARC70A', 'ARC70C', 'ARC70E'):
        if b in name.upper():
            return b
    return None

def main():
    with open(CSV_PATH, 'r', encoding='utf-8') as f:
        rows = list(csv.reader(f))
    data = [r for r in rows if r and r[0].startswith('svch')]

    series = {b: {
        'slug': meta[0], 'name': meta[1], 'group': meta[2], 'tu': meta[3],
        'description': meta[4], 'image': meta[5], 'imageByType': {}, 'items': []
    } for b, meta in SERIES_META.items()}

    for r in data:
        name = clean(r[1])
        b = detect(name)
        if not b: continue
        series[b]['items'].append({
            'name': name,
            'partnumber': clean(r[12]),
            'capacitance': clean(r[15]),
            'code': clean(r[16]),
            'case': clean(r[17]),
            'tolerance': (clean(r[18]) + (' … ' + clean(r[19]) if clean(r[19]) else '')).strip(),
            'temp': (clean(r[20]) + ' … ' + clean(r[21]) + ' °C').strip() if clean(r[20]) else '',
            'voltage': clean(r[24]),
            'datasheet': clean(r[30]),
        })

    order = ['main', 'dev']
    ordered = sorted(series.values(), key=lambda s: (order.index(s['group']), s['slug']))
    for s in ordered:
        print(f"  [{s['group']:4}] {s['name']:8} → {len(s['items'])} items")

    lines = [
        '// Auto-generated from 04_svch_kondensatory.csv. Do not edit manually.',
        '// Generated by _data/build-capacitors.py',
        '',
        'var CAPACITOR_SERIES = [',
    ]
    for s in ordered:
        lines.append('  {')
        lines.append(f'    slug: {json.dumps(s["slug"])},')
        lines.append(f'    name: {json.dumps(s["name"], ensure_ascii=False)},')
        lines.append(f'    group: {json.dumps(s["group"])},')
        lines.append(f'    tu: {json.dumps(s["tu"], ensure_ascii=False)},')
        lines.append(f'    description: {json.dumps(s["description"], ensure_ascii=False)},')
        lines.append(f'    image: {json.dumps(s["image"])},')
        lines.append(f'    imageByType: {{}},')
        lines.append(f'    count: {len(s["items"])},')
        lines.append('    items: [')
        for it in s['items']:
            lines.append('      ' + json.dumps(it, ensure_ascii=False) + ',')
        lines.append('    ]')
        lines.append('  },')
    lines.append('];')
    lines.append('')

    with open(OUT_PATH, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    total = sum(len(s['items']) for s in ordered)
    print(f"\nTotal: {total} items in {len(ordered)} series → {OUT_PATH}")

if __name__ == '__main__':
    main()
