#!/usr/bin/env python3
"""02_preobrazovateli.csv → js/converters-data.js"""
import csv, json, sys
sys.stdout.reconfigure(encoding='utf-8')

CSV_PATH = r"d:/site/_data/02_preobrazovateli.csv"
OUT_PATH = r"d:/site/js/converters-data.js"

BASE = '../assets/images/products/'

# Серия → (slug, display, group, tu, description, image)
SERIES_META = {
    'ИРТЫШ': ('irtysh',  'ИРТЫШ',  'main', '',
              'Модульные DC/DC преобразователи мощностью до 800 Вт. Входное напряжение 24/28/300/375 В.',
              BASE + 'items/Irtysh.webp'),
    'ВОЛГА': ('volga',   'ВОЛГА',  'dev',  '',
              'Модульные преобразователи напряжения серии ВОЛГА. В разработке.',
              BASE + 'converters.webp'),
    'ЕНИСЕЙ':('enisei',  'ЕНИСЕЙ', 'dev',  '',
              'Модульные преобразователи напряжения серии ЕНИСЕЙ. В разработке.',
              BASE + 'converters.webp'),
    'КАМА':  ('kama',    'КАМА',   'dev',  '',
              'Модульные преобразователи напряжения серии КАМА. В разработке.',
              BASE + 'converters.webp'),
}

def clean(s):
    return (s or '').strip().replace('\u00a0', ' ')

def detect_brand(name):
    u = name.upper()
    for b in ('ИРТЫШ', 'ВОЛГА', 'ЕНИСЕЙ', 'КАМА'):
        if b in u:
            return b
    return None

def main():
    with open(CSV_PATH, 'r', encoding='utf-8') as f:
        rows = list(csv.reader(f))

    data = [r for r in rows if r and r[0].startswith('proizvodstvo-preobrazovatelej')]

    series = {b: {
        'slug': meta[0], 'name': meta[1], 'group': meta[2], 'tu': meta[3],
        'description': meta[4], 'image': meta[5], 'imageByType': {}, 'items': []
    } for b, meta in SERIES_META.items()}

    for r in data:
        name = clean(r[1])
        brand = detect_brand(name)
        if not brand: continue
        series[brand]['items'].append({
            'name': name,
            'type': clean(r[12]),               # DC/DC / AC/DC
            'subseries': clean(r[13]),          # ET-F300 / ET-H300 / ...
            'partnumber': clean(r[14]),
            'vin': clean(r[15]),
            'vout': clean(r[16]),
            'case': clean(r[17]),
            'size': ' × '.join(x for x in [clean(r[18]), clean(r[19]), clean(r[20])] if x),
            'temp': clean(r[21]),
            'power': clean(r[22]),
            'current': clean(r[23]),
            'datasheet': clean(r[25]),
        })

    # Stats
    order = ['main', 'dev']
    ordered = sorted(series.values(), key=lambda s: (order.index(s['group']), s['slug']))
    for s in ordered:
        print(f"  [{s['group']:4}] {s['name']:8} → {len(s['items'])} items")

    # Generate JS
    lines = [
        '// Auto-generated from 02_preobrazovateli.csv. Do not edit manually.',
        '// Generated by _data/build-converters.py',
        '',
        'const CONVERTER_SERIES = [',
    ]
    for s in ordered:
        lines.append('  {')
        lines.append(f'    slug: {json.dumps(s["slug"])},')
        lines.append(f'    name: {json.dumps(s["name"], ensure_ascii=False)},')
        lines.append(f'    group: {json.dumps(s["group"])},')
        lines.append(f'    tu: {json.dumps(s["tu"], ensure_ascii=False)},')
        lines.append(f'    description: {json.dumps(s["description"], ensure_ascii=False)},')
        lines.append(f'    image: {json.dumps(s["image"])},')
        lines.append(f'    imageByType: {{}},')
        lines.append(f'    count: {len(s["items"])},')
        lines.append('    items: [')
        for it in s['items']:
            lines.append('      ' + json.dumps(it, ensure_ascii=False) + ',')
        lines.append('    ]')
        lines.append('  },')
    lines.append('];')
    lines.append('')

    with open(OUT_PATH, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    total = sum(len(s['items']) for s in ordered)
    print(f"\nTotal: {total} items in {len(ordered)} series → {OUT_PATH}")

if __name__ == '__main__':
    main()
