#!/usr/bin/env python3
"""04_svch_kondensatory.csv + scraped/names.json → js/capacitors-data.js"""
import csv, json, re, sys
sys.stdout.reconfigure(encoding='utf-8')

CSV_PATH = r"d:/site/_data/04_svch_kondensatory.csv"
SCRAPED = r"d:/site/_data/scraped/names.json"
OUT_PATH = r"d:/site/js/capacitors-data.js"

BASE = '../assets/images/products/'

SERIES_META = {
    'ARC70A': ('arc70a', 'ARC70A', 'main', 'ТКЕС.434410.002 ТУ',
               'Сверхвысокочастотные многослойные керамические чип-конденсаторы серии ARC70A.',
               BASE + 'items/ARC70A 1.webp'),
    'ARC70C': ('arc70c', 'ARC70C', 'main', '',
               'СВЧ-конденсаторы серии ARC70C. Ёмкость 0,5–3000 пФ, корпус 2225.',
               BASE + 'capacitors.webp'),
    'ARC70E': ('arc70e', 'ARC70E', 'main', '',
               'СВЧ-конденсаторы серии ARC70E. Сверхвысокочастотные многослойные керамические чип-конденсаторы.',
               BASE + 'capacitors.webp'),
}

def clean(s):
    return (s or '').strip().replace('\u00a0', ' ')

def detect(name):
    for b in ('ARC70A', 'ARC70C', 'ARC70E'):
        if b in name.upper(): return b
    return None

def parse_name_specs(name):
    out = {}
    m = re.search(r'(\d+(?:[.,]\d+)?)\s*пФ', name)
    if m: out['capacitance'] = m.group(1)
    return out

def main():
    with open(CSV_PATH, 'r', encoding='utf-8') as f:
        rows = list(csv.reader(f))
    csv_data = [r for r in rows if r and r[0].startswith('svch')]

    series = {b: {
        'slug': m[0], 'name': m[1], 'group': m[2], 'tu': m[3],
        'description': m[4], 'image': m[5], 'imageByType': {}, 'items': []
    } for b, m in SERIES_META.items()}

    # ARC70A — из CSV
    for r in csv_data:
        name = clean(r[1])
        b = detect(name)
        if b != 'ARC70A': continue
        series[b]['items'].append({
            'name': name,
            'partnumber': clean(r[12]),
            'capacitance': clean(r[15]),
            'code': clean(r[16]),
            'case': clean(r[17]),
            'tolerance': (clean(r[18]) + (' … ' + clean(r[19]) if clean(r[19]) else '')).strip(),
            'temp': (clean(r[20]) + ' … ' + clean(r[21]) + ' °C').strip() if clean(r[20]) else '',
            'voltage': clean(r[24]),
            'datasheet': clean(r[30]),
        })

    # ARC70C / ARC70E — из scraped
    with open(SCRAPED, 'r', encoding='utf-8') as f:
        scraped = json.load(f)
    for brand_key, scrape_key in [('ARC70C','arc70c'), ('ARC70E','arc70e')]:
        seen = set()
        for name in scraped.get(scrape_key, []):
            name = clean(name)
            if name in seen: continue
            seen.add(name)
            specs = parse_name_specs(name)
            item = {'name': name}
            item.update(specs)
            series[brand_key]['items'].append(item)

    order_group = ['main', 'dev']
    order_slug = ['arc70a', 'arc70c', 'arc70e']
    ordered = sorted(series.values(), key=lambda s: (order_group.index(s['group']), order_slug.index(s['slug']) if s['slug'] in order_slug else 99))
    for s in ordered:
        print(f"  [{s['group']:4}] {s['name']:8} → {len(s['items'])} items")

    lines = [
        '// Auto-generated from 04_svch_kondensatory.csv + scraped/names.json.',
        '// Generated by _data/build-capacitors.py',
        '',
        'var CAPACITOR_SERIES = [',
    ]
    for s in ordered:
        lines.append('  {')
        lines.append(f'    slug: {json.dumps(s["slug"])},')
        lines.append(f'    name: {json.dumps(s["name"], ensure_ascii=False)},')
        lines.append(f'    group: {json.dumps(s["group"])},')
        lines.append(f'    tu: {json.dumps(s["tu"], ensure_ascii=False)},')
        lines.append(f'    description: {json.dumps(s["description"], ensure_ascii=False)},')
        lines.append(f'    image: {json.dumps(s["image"])},')
        lines.append(f'    imageByType: {{}},')
        lines.append(f'    count: {len(s["items"])},')
        lines.append('    items: [')
        for it in s['items']:
            lines.append('      ' + json.dumps(it, ensure_ascii=False) + ',')
        lines.append('    ]')
        lines.append('  },')
    lines.append('];')
    lines.append('')

    with open(OUT_PATH, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    total = sum(len(s['items']) for s in ordered)
    print(f"\nTotal: {total} items in {len(ordered)} series → {OUT_PATH}")

if __name__ == '__main__':
    main()
